import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "on-surface-variant": "#4c4546",
        "outline-variant": "#cfc4c5",
        "on-surface": "#1a1c1c",
        "secondary-fixed": "#e2e3e2",
        secondary: "#5d5f5f",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3131",
        "surface-container-highest": "#e2e2e2",
        "secondary-fixed-dim": "#c6c7c6",
        surface: "#f9f9f9",
        "on-secondary-fixed": "#1a1c1c",
        "primary-fixed": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#46464e",
        "secondary-container": "#e2e3e2",
        tertiary: "#000000",
        "tertiary-container": "#1a1b22",
        "on-primary-fixed-variant": "#474747",
        "surface-tint": "#5e5e5e",
        "on-primary-fixed": "#1b1b1b",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-container-low": "#f3f3f3",
        "tertiary-fixed": "#e3e1ec",
        "on-tertiary": "#ffffff",
        "surface-lowest": "#ffffff",
        primary: "#000000",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary-container": "#83838c",
        "tertiary-fixed-dim": "#c6c5cf",
        "inverse-primary": "#c6c6c6",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#454747",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#1a1b22",
        "error-container": "#ffdad6",
        "on-secondary-container": "#636565",
        outline: "#7e7576",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        gutter: "24px",
        "section-gap": "128px",
      },
      fontFamily: {
        display: ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        code: ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
